//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.1
//     from Assets/ControlLayout.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlLayout : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlLayout()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlLayout"",
    ""maps"": [
        {
            ""name"": ""PlayerControls"",
            ""id"": ""5858bdea-1873-4d50-8d0f-a67e799fed07"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""3debf876-7c5f-40b3-a270-4e1d4621829c"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""16e4eefe-b7ac-4343-a4c3-5c6cccfb073e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""87b530f2-4e23-4883-860c-de3f2d05fb8a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Slide"",
                    ""type"": ""Button"",
                    ""id"": ""5f818aa3-8379-451a-a94a-db0891cf8572"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""a8c6badb-d6bd-4eb1-b485-e9f34a4143c2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""3c443938-cea1-480d-9be6-d5bebb6d9e14"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""edc71b7c-018b-4a27-b196-5fc6c5e9a26b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0415fc54-4794-4b00-908a-7d6fe513c7e3"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1039d86c-5587-45fc-9b5a-a6b3ad305ab6"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""b5faa6f3-e21b-4a4f-a97f-637c9a903c93"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""dab7fead-8d9b-417a-a553-a078396691d9"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""72a6e351-84da-4efb-9c0b-33d69bbbe1eb"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9bb0ab54-03d1-4291-84ec-713104d74757"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""fb0eb639-2f69-4d66-ab0a-a69a0e8c83ee"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""2a484e46-3720-46de-8b35-158dadb80a02"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f610c8c0-1402-473e-a3f8-94646086101e"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""85f55f07-29f9-4adf-b6ab-6aef888c4f10"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Slide"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PlayerAbilities"",
            ""id"": ""032b689f-042b-4748-9b57-aeaddcdcddda"",
            ""actions"": [
                {
                    ""name"": ""CastLightBeam"",
                    ""type"": ""Button"",
                    ""id"": ""5ed9a46b-e62b-42ac-b03f-770ee27290e9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Teleport"",
                    ""type"": ""Button"",
                    ""id"": ""a507b76d-b970-4b70-84f0-873c99b7d76a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CancelTeleport"",
                    ""type"": ""Button"",
                    ""id"": ""e505b8c7-9d61-47d0-acf7-2c0f84bcc20f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LightMode"",
                    ""type"": ""Button"",
                    ""id"": ""e4aae941-197a-49b3-84c5-460faf0b5c34"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Push/Pull"",
                    ""type"": ""Button"",
                    ""id"": ""0bc5117b-1f84-42b6-b5bd-58c8531b3130"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c09f5c14-48c6-4870-a6a7-23dc8724ee8f"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CastLightBeam"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d1ed4c4-2ff6-453b-99b5-353b60cc1a21"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Teleport"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""65ab73b3-8adb-4a56-b047-a5010434c0c1"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CancelTeleport"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24b284d0-b3ca-4969-9288-c1612b7fd0dc"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LightMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7315dfd6-757e-493d-9a8f-0983f51a2c80"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Push/Pull"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerControls
        m_PlayerControls = asset.FindActionMap("PlayerControls", throwIfNotFound: true);
        m_PlayerControls_Movement = m_PlayerControls.FindAction("Movement", throwIfNotFound: true);
        m_PlayerControls_Jump = m_PlayerControls.FindAction("Jump", throwIfNotFound: true);
        m_PlayerControls_Sprint = m_PlayerControls.FindAction("Sprint", throwIfNotFound: true);
        m_PlayerControls_Slide = m_PlayerControls.FindAction("Slide", throwIfNotFound: true);
        // PlayerAbilities
        m_PlayerAbilities = asset.FindActionMap("PlayerAbilities", throwIfNotFound: true);
        m_PlayerAbilities_CastLightBeam = m_PlayerAbilities.FindAction("CastLightBeam", throwIfNotFound: true);
        m_PlayerAbilities_Teleport = m_PlayerAbilities.FindAction("Teleport", throwIfNotFound: true);
        m_PlayerAbilities_CancelTeleport = m_PlayerAbilities.FindAction("CancelTeleport", throwIfNotFound: true);
        m_PlayerAbilities_LightMode = m_PlayerAbilities.FindAction("LightMode", throwIfNotFound: true);
        m_PlayerAbilities_PushPull = m_PlayerAbilities.FindAction("Push/Pull", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerControls
    private readonly InputActionMap m_PlayerControls;
    private IPlayerControlsActions m_PlayerControlsActionsCallbackInterface;
    private readonly InputAction m_PlayerControls_Movement;
    private readonly InputAction m_PlayerControls_Jump;
    private readonly InputAction m_PlayerControls_Sprint;
    private readonly InputAction m_PlayerControls_Slide;
    public struct PlayerControlsActions
    {
        private @ControlLayout m_Wrapper;
        public PlayerControlsActions(@ControlLayout wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerControls_Movement;
        public InputAction @Jump => m_Wrapper.m_PlayerControls_Jump;
        public InputAction @Sprint => m_Wrapper.m_PlayerControls_Sprint;
        public InputAction @Slide => m_Wrapper.m_PlayerControls_Slide;
        public InputActionMap Get() { return m_Wrapper.m_PlayerControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerControlsActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerControlsActions instance)
        {
            if (m_Wrapper.m_PlayerControlsActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnMovement;
                @Jump.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnJump;
                @Sprint.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnSprint;
                @Sprint.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnSprint;
                @Sprint.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnSprint;
                @Slide.started -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnSlide;
                @Slide.performed -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnSlide;
                @Slide.canceled -= m_Wrapper.m_PlayerControlsActionsCallbackInterface.OnSlide;
            }
            m_Wrapper.m_PlayerControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Sprint.started += instance.OnSprint;
                @Sprint.performed += instance.OnSprint;
                @Sprint.canceled += instance.OnSprint;
                @Slide.started += instance.OnSlide;
                @Slide.performed += instance.OnSlide;
                @Slide.canceled += instance.OnSlide;
            }
        }
    }
    public PlayerControlsActions @PlayerControls => new PlayerControlsActions(this);

    // PlayerAbilities
    private readonly InputActionMap m_PlayerAbilities;
    private IPlayerAbilitiesActions m_PlayerAbilitiesActionsCallbackInterface;
    private readonly InputAction m_PlayerAbilities_CastLightBeam;
    private readonly InputAction m_PlayerAbilities_Teleport;
    private readonly InputAction m_PlayerAbilities_CancelTeleport;
    private readonly InputAction m_PlayerAbilities_LightMode;
    private readonly InputAction m_PlayerAbilities_PushPull;
    public struct PlayerAbilitiesActions
    {
        private @ControlLayout m_Wrapper;
        public PlayerAbilitiesActions(@ControlLayout wrapper) { m_Wrapper = wrapper; }
        public InputAction @CastLightBeam => m_Wrapper.m_PlayerAbilities_CastLightBeam;
        public InputAction @Teleport => m_Wrapper.m_PlayerAbilities_Teleport;
        public InputAction @CancelTeleport => m_Wrapper.m_PlayerAbilities_CancelTeleport;
        public InputAction @LightMode => m_Wrapper.m_PlayerAbilities_LightMode;
        public InputAction @PushPull => m_Wrapper.m_PlayerAbilities_PushPull;
        public InputActionMap Get() { return m_Wrapper.m_PlayerAbilities; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerAbilitiesActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerAbilitiesActions instance)
        {
            if (m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface != null)
            {
                @CastLightBeam.started -= m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface.OnCastLightBeam;
                @CastLightBeam.performed -= m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface.OnCastLightBeam;
                @CastLightBeam.canceled -= m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface.OnCastLightBeam;
                @Teleport.started -= m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface.OnTeleport;
                @Teleport.performed -= m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface.OnTeleport;
                @Teleport.canceled -= m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface.OnTeleport;
                @CancelTeleport.started -= m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface.OnCancelTeleport;
                @CancelTeleport.performed -= m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface.OnCancelTeleport;
                @CancelTeleport.canceled -= m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface.OnCancelTeleport;
                @LightMode.started -= m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface.OnLightMode;
                @LightMode.performed -= m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface.OnLightMode;
                @LightMode.canceled -= m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface.OnLightMode;
                @PushPull.started -= m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface.OnPushPull;
                @PushPull.performed -= m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface.OnPushPull;
                @PushPull.canceled -= m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface.OnPushPull;
            }
            m_Wrapper.m_PlayerAbilitiesActionsCallbackInterface = instance;
            if (instance != null)
            {
                @CastLightBeam.started += instance.OnCastLightBeam;
                @CastLightBeam.performed += instance.OnCastLightBeam;
                @CastLightBeam.canceled += instance.OnCastLightBeam;
                @Teleport.started += instance.OnTeleport;
                @Teleport.performed += instance.OnTeleport;
                @Teleport.canceled += instance.OnTeleport;
                @CancelTeleport.started += instance.OnCancelTeleport;
                @CancelTeleport.performed += instance.OnCancelTeleport;
                @CancelTeleport.canceled += instance.OnCancelTeleport;
                @LightMode.started += instance.OnLightMode;
                @LightMode.performed += instance.OnLightMode;
                @LightMode.canceled += instance.OnLightMode;
                @PushPull.started += instance.OnPushPull;
                @PushPull.performed += instance.OnPushPull;
                @PushPull.canceled += instance.OnPushPull;
            }
        }
    }
    public PlayerAbilitiesActions @PlayerAbilities => new PlayerAbilitiesActions(this);
    public interface IPlayerControlsActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
        void OnSlide(InputAction.CallbackContext context);
    }
    public interface IPlayerAbilitiesActions
    {
        void OnCastLightBeam(InputAction.CallbackContext context);
        void OnTeleport(InputAction.CallbackContext context);
        void OnCancelTeleport(InputAction.CallbackContext context);
        void OnLightMode(InputAction.CallbackContext context);
        void OnPushPull(InputAction.CallbackContext context);
    }
}
